# TODO replace name with name of ebook: 101: Intro to Web, 411: Front-Ends with React...etc
site_name: Web 101 - Intro to the Web

# To get started:
# 1. TODO inside `ebook-folder/`
# 2. TODO run `git clone https://github.com/squidfunk/mkdocs-material.git`
# 3. TODO run `pip install -r requirements.txt` (see inside mkdocs-material/)
# 4. TODO run `mkdocs build` to build the static files into "/site"
# 5. TODO run `mkdocs serve` to serve those files to http://127.0.0.1:8000
# 6. TODO replace all CAPITALIZED words with appropriate titles
# ! Use the files in workspace/resources to quickly generate class and lesson templates, see `cp ...` script at bottom of each file
# ! Use the folder workspace/developmentDocumentation to record thoughts and future improvements

# defines where the markdown to build from
# docs_dir: 'test-node-book'

# defines where to put the generated static files
# site_dir: 'docs'

# use this to create the nav bar on the left-side of the window view

nav:
    - Home: 'index.md'
    - 'Self-Paced Prep':
      - 'Your first web page':
        - Building our first web page: preCourse/ourFirstWebPage.md
        - Let's Write Some Code: preCourse/letsWriteSomeCode.md
        - CSS For Looks: preCourse/cssForLooks.md
        - How The Web Works: preCourse/day1-homework.md
      - 'HTML':
        - HTML Tags: preCourse/htmlTags.md
        - Code Sandboxes : preCourse/codeSandboxes.md
        - HTML Attributes: preCourse/htmlAttributes.md
        - Semantic Elements: preCourse/day2-homework.md
      - 'Cascading Style Sheets':  
        - CSS Getting Started: preCourse/cssGettingStarted.md
        - CSS Intro : preCourse/cssIntro.md
        - CSS Principles: preCourse/moreCSStechniques.md
        - The Box Model: module-1/theBoxModel.md
        - Width & Height: module-1/boxModel-width&height.md
        - Padding: module-1/boxModel-padding.md
        - Border: module-1/boxModel-border.md
        - Margin: module-1/boxModel-margin.md
        - Characters To Know: preCourse/charactersToKnow.md
        - Keyboard Practice: preCourse/keyboardQuiz.md
      - 'Day 4 Program Prep':
        - Flipped Classroom: preCourse/succeedInThisCourse.md
        - Develop Series: preCourse/theDevelopSeries.md
        - SAT Method: preCourse/theSATmethod.md
        - Blogging Habit: preCourse/whyBlogging.md
        - Submitting Homework: preCourse/submittingHomework.md

    # cp workspace/resources/templateFile.md docs/module-
    - 'Module One: Page Layout':
      - 'Pre-Class 1 Lessons': 
        - Class 1 Landing Page: module-1/class-1.md
      - 'Pre-Class 2 Lessons': 
        - Display Property: module-1/displayProperty.md
        - Display Flex: module-1/displayFlexProperties.md
        - Flex Item: module-1/flexItemProperties.md
        - Develop - Self-Motivation: module-1/developSeries-selfMotivation.md
        - Class 2 NASA Page: module-1/class-2.md
      - 'Pre-Class 3 Lessons':
        - Develop - Mindfulness: module-1/developSeries-mindfulness.md
        - Wireframing: module-1/wireframing-pt1.md
        - Display Grid: module-1/displayGrid.md
        - Grid Properties: module-1/moreGridProperties.md
        - Class 3 Resume: module-1/class-3.md
      - 'Pre-Class 4 Lessons': 
        - Responsive Layouts: module-1/responsiveLayouts-gridAreas.md     
        - Media Queries: module-1/mediaQueries.md  
        - More CSS Selectors: module-1/moreCssSelectors.md
        - CSS Specificity: module-1/specificityAndCombinators.md
        - Develop - Letting Go of Self-Importance: module-1/developSeries-lettingGoOfShame.md
        - Class 4: module-1/class-4.md
    - 'Module Two: Interactions': 
      - 'Pre-Class 5 Lessons': 
        - Intro to JavaScript: module-2/introToJavaScript.md
        - How the Internet Works: module-2/howTheInternetWorks.md
        - Our Job: module-2/ourJobAsWebDevelopers.md
        - Ways Of Thinking: module-2/waysOfThinking.md
        - Two Perspectives: module-2/twoPerspectives.md
        - The DOM + JS Intro pt.2: module-2/theDOM-jsIntro-pt2.md
        - Table and nth Child: module-2/table-nthChild.md
        - Class 5 TicTacToe + About: module-2/class-5.md
      - 'Pre-Class 6 Lessons':
        # TODO - Develop - TITLE: module-2/.md
        - HTTProtocol: module-2/HTTP-req-res.md
        - HTML Elements: module-2/htmlElements.md
        - Form Element: module-2/formElement.md
        - Button Element: module-2/buttonElement.md
        - Input Element: module-2/inputElement.md
        - Event Listeners: module-2/commonEventListeners.md
        - Class 6 Contact Page: module-2/class-6.md
      - 'Pre-Class 7 Lessons': 
        - Develop - Your Brain: module-2/developSeries-brainBuilding.md
        - Window Methods: module-2/windowMethods.md
        - Document Methods: module-2/documentMethods.md
        - Image Element: module-2/imageElement.md
        - Class 7 Calculator App: module-2/class-7.md
      - 'Pre-Class 8 Lessons':
        # TODO - Develop - TITLE: module-2/.md
        - Video & Iframe Elements: module-2/video-iframe-elements.md
        - Class 8 Checkpoint: module-2/class-8.md
    - 'Module Three: Programming': 
      - 'Pre-Class 9 Lessons':
        - Develop - Cure Imposter Syndrome: module-3/developSeries-cureImposterSyndrome.md
        - The Console Object: module-3/consoleObject.md
        - JS Function Syntax: module-3/jsFunctionSyntax.md
        - Type Array: module-3/typeArray.md
        - Intro To Loops: module-3/introToLoops.md
        - Class 9 EvenOdd List: module-3/class-9.md
      - 'Pre-Class 10 Lessons': 
        - Develop - Handle Your Feeling: module-3/developSeries-handleFeelings.md
        - Git Branch Review: module-3/gitBranchReview.md
        - Nested Arrays: module-3/nestedArrays.md
        - Class 10 TicTacToe: module-3/class-10.md
      - 'Pre-Class 11 Lessons':
        - Develop - Attention & Collaborators: module-3/developSeries-attentionAndCollaboration.md
        - Intro to APIs: module-3/introToAPIs.md
        - HTML Fetch API: module-3/html-FetchAPI.md
        - Asynchronous Code: module-3/asynchronousCode.md
        - Type Object-Literal: module-3/objectLiterals.md
        - Class 11 ToDo List: module-3/class-11.md
      - 'Pre-Class 12 Lessons': 
        - Develop - Build Your Network: module-3/buildYourNetwork.md
        - Code Planning: module-3/howToPlan.md
        - Using Trello: module-3/usingTrello.md
        - Intro to Filtering: module-3/introToFiltering.md
        - Class 12 Filtering ToDos: module-3/class-12.md
    - 'Module Four: API & Animation':
      - 'Pre-Class 13 Lessons':
        - Develop Emotions vs Feelings: module-4/developSeries-feelingsVsEmotions.md
        - CSS Reset: module-4/cssReset.md
        - Git Merge Conflicts: module-4/mergeConflicts.md
        - Intro to Animations: module-4/animationIntro.md
        - Intro to Transformations: module-4/introToTransformations.md
        - Intro to Transitions: module-4/introToTransitions.md
        - Class 13: module-4/class-13.md
      - 'Pre-Class 14 Lessons': 
        - Develop, Life Happens: module-4/developSeries-lifeHappensForYou.md
        - Parallax: module-4/introToParallax.md
        - Bootstrap: module-4/introToBootstrap.md
        - Bootstrap Modals: module-4/modalsWithBootstrap.md
        - HTML API - Canvas pt.1: module-4/htmlAPI-canvas-pt1.md
        - Class 14: module-4/class-14.md
      - 'Pre-Class 15 Lessons': 
        - Develop Your Goals: module-4/developSeries-achievingGoals.md
        - The HTML5 APIs: module-4/html5-apis.md
        - Geolocation API: module-4/geolocationAPI.md
        - Drag & Drop API: module-4/dragAndDropAPI.md
        - Class 15: module-4/class-15.md
      - 'Pre-Class 16 Lessons':  
        - Develop Teaching Yourself: module-4/developSeries-TeachingYourself.md
        - HTML API - Canvas pt.2: module-4/htmlAPI-canvas-pt2.md
        - Talking Code: module-4/talkingCode.md
        - Class 16: module-4/class-16.md
      
      # https://vimeo.com/manage/folders/1059416
      #   - The Three Actions of Data: module-1/lesson-4.md
      #   - Get Data: module-1/lesson-5.md
      #   - Store Data: module-1/lesson-6.md
      #   - Render Data: module-1/lesson-7.md
      #   - Reading Docs: module-1/lesson-8.md
    - Report A Bug: additionalResources/reportABug.md
    - 'Additional Resources':
      - Interview Training: additionalResources/interviewChallenges.md
      - Student Presentations: additionalResources/studentPresentations.md
      - Develop Series Collection: additionalResources/developSeries.md
      - 'Questions for Discussion Collections':
        - Day 1 QFD: additionalResources/questionsForDiscussion/qfd-class-1.md
        - Day 2 QFD: additionalResources/questionsForDiscussion/qfd-class-2.md
        - Day 3 QFD: additionalResources/questionsForDiscussion/qfd-class-3.md
        - Day 4 QFD: additionalResources/questionsForDiscussion/qfd-class-4.md
        - Day 5 QFD: additionalResources/questionsForDiscussion/qfd-class-5.md
        - Day 6 QFD: additionalResources/questionsForDiscussion/qfd-class-6.md
        - Day 7 QFD: additionalResources/questionsForDiscussion/qfd-class-7.md
        - Day 8 QFD: additionalResources/questionsForDiscussion/qfd-class-8.md
        - Day 9 QFD: additionalResources/questionsForDiscussion/qfd-class-9.md
        - Day 10 QFD: additionalResources/questionsForDiscussion/qfd-class-10.md
        - Day 11 QFD: additionalResources/questionsForDiscussion/qfd-class-11.md
        - Day 12 QFD: additionalResources/questionsForDiscussion/qfd-class-12.md
        - Day 13 QFD: additionalResources/questionsForDiscussion/qfd-class-13.md
        - Day 14 QFD: additionalResources/questionsForDiscussion/qfd-class-14.md
        - Day 15 QFD: additionalResources/questionsForDiscussion/qfd-class-15.md
        - Day 16 QFD: additionalResources/questionsForDiscussion/qfd-class-16.md
      - Blog Prompts: additionalResources/blogPrompts.md
      - Keyboard Shortcuts: additionalResources/keyboardShortcuts.md
      - 'Git & GitHub':
        - Prepare Your Machine: additionalResources/setupInstructions.md
        - GitHub Overview: additionalResources/gitOverhere.md
        - Git & GitHub Setup: additionalResources/gitAndGitHub.md
        - Git Setup Check-in: additionalResources/gitAndGitHub.md
        - Git Setup: additionalResources/gitSetup.md
        - Git Basics: additionalResources/gitBasics.md
        - Git & CLI Commands: additionalResources/gitCommands.md
      - Portfolio Landing Page: additionalResources/project-LandingPage.md
      - Graduation Prerequisites: additionalResources/graduationPrerequisites.md
      - Presentation Qualifications: additionalResources/presentationsQualifications.md
      - 'Bonus Materials':
      # add these resources in https://studio.zollege.com/container/block-v1:ACA+PW101+2021-Feb2+type@vertical+block@9e36b68dc98048238efe59e87cc619d1
        - additionalResources/bonusMaterial/evenOddFollowAlong.md

# defines the styles, usually just a single name but `custom_dir` overrides this behavior
theme:
  name: material
  # was null
  palette:
    scheme: slate
    primary: black
    accent: deep orange
    # Defines the logo in the top-left, file must be in the /doc directory
  logo: CE_WhiteBlue_Icon.png
  
  # ? Not rendering as expected??
  extra:
    copyright: Copyright &copy; 2013 - 2021 Austin Coding Academy
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/AustinCodingAcademy
      - icon: fontawesome/brands/medium
        link: https://medium.com/@austincoding
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/school/austincodingacademy/
      - icon: fontawesome/brands/instagram
        link: https://www.instagram.com/austincodingacademy
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/austincoding
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/AustinCodingAcademy/


  
  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      clickable_checkbox: true
  - def_list
  - pymdownx.tabbed


 

# Can add icons throughout the ebook https://materialdesignicons.com/
#  - pymdownx.inlinehilite
  # - pymdownx.keys